DROP TABLE IF EXISTS "users";

DROP TABLE IF EXISTS "projects";

-- Criação da Tabela Users
CREATE TABLE
  "users" (
    "user_id" INT GENERATED BY DEFAULT AS IDENTITY,
    "first_name" VARCHAR(50),
    "last_name" VARCHAR(50),
    "email" VARCHAR(100) UNIQUE NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "avatar" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("user_id")
  );

-- Criação da Tabela Projects
CREATE TABLE
  "projects" (
    "project_id" INT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT,
    "title" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "tags" TEXT,
    "link" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id")
  );

-- INSERÇÃO
INSERT INTO
  users (
    "first_name",
    "last_name",
    "email",
    "password_hash",
  )
VALUES
  (
    'Bianca',
    'Martin',
    'bianca.mar@orange.dev',
    'pass',
  ),
  ('Enzo', 'Gabriel', 'enzo.gab@orange.dev', 'pass',),
  (
    'Alice',
    'Alexandra',
    'aice.ale@orange.dev',
    'pass',
  );

INSERT INTO
  contacts (user_id, contact_name, phone, email)
VALUES
  (
    1,
    'John Doe',
    '(408)-111-1234',
    'john.doe@orange.dev'
  ),
  (
    1,
    'Jane Doe',
    '(408)-111-1235',
    'jane.doe@orange.dev'
  ),
  (
    2,
    'David Wright',
    '(408)-222-1234',
    'david.wright@dolphin.dev'
  );